---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  cap_add:
    - SYS_PTRACE
    - SYS_ADMIN

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt::default]

  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt::default]

  - name: debian-8
    driver:
      image: dokken/debian-8
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt::default]

  - name: debian-9
    driver:
      image: dokken/debian-9
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt::default]

  - name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init

  - name: centos-7
    driver:
      image: dokken/centos-7
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /usr/lib/systemd/systemd

  - name: centos-8
    driver:
      image: dokken/centos-8
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /usr/lib/systemd/systemd

  - name: centos-stream-8
    driver:
      image: dokken/centos-stream-8
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /usr/lib/systemd/systemd

  - name: fedora-34
    driver:
      image: dokken/fedora-34
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      pid_one_command: /usr/lib/systemd/systemd
...
