---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  chef_license: accept
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: always
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

platforms:
- name: ubuntu-18.04
  run_list:
  - recipe[apt]
- name: ubuntu-16.04
  run_list:
  - recipe[apt]
- name: debian-8.11
  run_list:
  - recipe[apt]
- name: debian-9.6
  run_list:
  - recipe[apt]
- name: centos-6.10
- name: centos-7.6
- name: fedora-34

verifier:
  name: inspec

suites:
- name: default
  run_list:
    - recipe[bind::default]
- name: resources
  run_list:
    - recipe[bind_test]
- name: chroot
  excludes:
    - ubuntu-16.04
  run_list:
    - recipe[bind_test::chroot]
- name: views
  includes:
    - centos-8
  run_list:
    - recipe[bind_test::views]
- name: logging
  includes:
    - centos-8
  run_list:
    - recipe[bind_test::logging]
- name: linked-zones
  includes:
    - ubuntu-16.04
    - debian-9.6
  run_list:
    - recipe[bind_test::linked_zones]
...
